language: go
go: '1.7'
install:
- wget https://github.com/gohugoio/hugo/releases/download/v0.24.1/hugo_0.24.1_Linux-64bit.tar.gz
- tar xzf hugo_0.24.1_Linux-64bit.tar.gz
- export PATH=$PATH:$PWD
script: ./bin/build
deploy:
  provider: cloudfoundry
  skip_cleanup: true
  api: https://api.run.pivotal.io
  username: pengblog-sa-1
  organization: pivotal
  space: blog
  on:
    repo: pivotal-legacy/blog
    branch: master
  password:
    secure: gd75PtNvDs6gabtlde7Yzg7BxHrJQ2gp05uSs5xTEfZ4LFfOO9TIVedr/yilnd4C42j2XrfpjbJFKJDVk3DlmpA0jqt0WJguBO9e3Ehth+adV8yRF2ysA00CSwOro8nx+JFnE5Xyr3MkZ75g5YjU23j+P43xyxwBfjvRK1PLghU8oCSK0ju7rTmpI8U8z+NZdlS1j+KqdcEPO2caoldIjVMf/FawEnhCppQHygewGugVOCmDycpDOfLRwJHdbopMNjt0YvJzdv5unhBYK+VTwOPHpT+Je+8lbit4HI1/Fyqma3GZmsTQeI90cqgzHlyee1FBth8num0L+TO2dGgq5SlgnUvRToGK2J/59OIRMXKmh7CyniBRR27rHOUK6SG7V9a4JUGxGUXv+piAOEsSsoLwdVEw9nEIR0pzqchnyxjFoX1cMrRJr+cxEJveb+O7Daa0YABEwimx7826KFLxBz/4gSEKtt1fJuKIPSYJsNper4zobIxV5xadKOOGKh9F9NZc7Y6+6fTorAaoxldfE6PbyH1v3DgRYwQURTUGveqnXvDQHhTVSTTtrutmwAPcaPrMIhDAd1FxIO4qyI5NMgfEkp8ND4inC26E3jsWsXDW48JpnTwyShJ5Osq0oSpaimtCGYQUM26vBxLnmoikABWrm3JSnfah/qEqA3tPmOE=
notifications:
  slack:
    secure: gzsa/wyD5IE/9Mzao33A4jtyPbqu3UI7cE3RaWy3i04G5U+7zmVIurpxlMMhp62RmKpr0r40suKJ40F3tRn2/FQbqpWZ39MWkfP8DNg0JDGHLOsG6HpuAC8dwSAs1TrnK+K/L+zzKJzGPEnZ/vhymMtC4htkLPCtwJTvomo6RCTFAc4F/S49EdD/6S/A7AATrOrSOWjZ8nfM71/lF6OvwmODVVGk0C2vg4kFE2W3icQaoSJ2dkO5Y1vgHSXtivXmvHG7y5MCDVHnwyxgWN7e1l5ELTVNHP8v9DxUBTN6ILtaBwpy1R3G6997TPJEGVfaAEek0pUpbNpXg4Pv6Cirmq1byoBOx693DUmyZRqOWGhg9yHicNr2AM3dc7eVpoD+ckeqmbgnX53sPd5eSlntbRys9YqdF0TVlkuOK40valUwBeo7bNsD7gU5hkXRI/v0pVUNODJbnVi43vsY6zCcSek2phi0hvwnI1t2toy8w6d2HuwkSq3czOkJPuzUhQhnqZASdZTUmTyymaPlEwVfv5M4956WMA3Zg75WcunYzB2E18Kp6DYA3CSRV3NCT8P6HFysOX0lpvHEDXl6S1weWkpbK+lXkrYkyhrV4uim+b+49g+kqgJpuHmhCyLlxMXlI3Dzb7Rn6MMKLJCwxjmenoqm6/LsJY7jdkwz2ojYfvs=
