languageCode: en-us
Theme: "pivotal-ui"
Title: Pivotal Engineering Journal
taxonomies:
  tag: "tags"
  category: "categories"
  author: "authors"
Params:
  SubTitle: Technical articles from Pivotal engineers.
baseURL: "https://engineering.pivotal.io"
googleAnalytics: UA-39702075-1
rssLimit: 25
markup:
  highlight:
    style: native
...
